### ISSUE TITLE
Drag Right Sidebar broken

### ISSUE THREAD

**Issue by ravingdragoon** [tirzah2/DragEverything#1]
The Right sidebar is currently being forced to the left of my screen and I am unable to drag it or resize it. I have only this module and the following "library" modules enabled, using Find The Culprit, and I still encounter the issue.
Foundry V12 Build 330
DnD System 3.3.1 

![image](https://github.com/user-attachments/assets/d8dd1a79-117a-4720-9367-3bc4ae13866c)

**Comment by Ironxxx** [comment]
Also get this with no means to move the right sidebar, this is teh sidebar that contains the chat window and all options.

**Comment by Ironxxx** [comment]
```
Error: Error thrown in hooked function '' for hook 'renderSidebarTab'. $(...).draggable is not a function
[Detected 1 package: drageverything(1.3)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at SceneDirectory._callHooks (foundry.js:5917:13)
    at SceneDirectory._render (foundry.js:5878:10)
    at async SceneDirectory._render (foundry.js:72744:5)Caused by: TypeError: $(...).draggable is not a function
[Detected 1 package: drageverything(1.3)]
    at makeElementDraggable (script.js:72:20)
    at makeSidebarDraggable (script.js:198:5)
    at Object.fn (script.js:227:5)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at SceneDirectory._callHooks (foundry.js:5917:13)
    at SceneDirectory._render (foundry.js:5878:10)
    at async SceneDirectory._render (foundry.js:72744:5)
```
